In [21]:
import scraping_functions as sf
import pandas as pd

In [22]:
nofluffjobs_list = sf.nofluffjobs_page_job_offers()
df_raw_1 = pd.DataFrame.from_records(nofluffjobs_list)
df_1 = df_raw_1.copy()
df_1['publication_date'] = pd.to_datetime(df_1['publication_date'], infer_datetime_format=True)
df_1.drop_duplicates(subset=['publication_date', 'company', 'title'], inplace=True, ignore_index=True)

IndexError: list index out of range

In [ ]:
df_1

,publication_date,company,title,position,link_url
0,2022-08-18,Amartus Polska Sp. z o.o.,Junior Phyton Developer,Junior,http://nofluffjobs.com/pl/job/junior-phyton-de...
1,2022-08-18,IDEA team within Narodowe Centrum Badań Jądrowych,Junior Python Developer,Junior,http://nofluffjobs.com/pl/job/junior-python-de...
2,2022-08-18,Devire,Python Developer (Data Science),Junior,http://nofluffjobs.com/pl/job/python-developer...
3,2022-08-20,Deloitte Advisory,AI LAB,Trainee,http://nofluffjobs.com/pl/job/ai-lab-deloitte-...
4,2022-08-19,Webinterpret,Junior Data Scientist,Junior,http://nofluffjobs.com/pl/job/junior-data-scie...
5,2022-08-08,Sport Vision Technology sp. z o.o. sp. k.,Junior AI Developer,Junior,http://nofluffjobs.com/pl/job/junior-ai-develo...
6,2022-08-17,Astrotectonic,Junior Data Scientist,Junior,http://nofluffjobs.com/pl/job/junior-data-scie...

In [ ]:
bulldogjob_list = sf.bulldog_page_job_offers()
df_raw_2 = pd.DataFrame.from_records(bulldogjob_list)
df_2 = df_raw_2.copy()
df_2['publication_date'] = pd.to_datetime(df_2['publication_date'], infer_datetime_format=True)
df_2.drop_duplicates(subset=['publication_date', 'company', 'title'], inplace=True, ignore_index=True)

In [ ]:
df_2

,publication_date,company,title,position,link_url
0,2022-07-23,Accenture Polska,Junior Data Engineer with Python (Communicatio...,Junior,https://bulldogjob.pl/companies/jobs/120362-ju...
1,2022-08-14,Bertek Sp. z o.o.,Junior Python Developer,Junior,https://bulldogjob.pl/companies/jobs/113373-ju...

In [ ]:
df_3 = pd.concat([df_1, df_2], axis=0, ignore_index=True)
df_3.sort_values(['publication_date'], inplace=True, ascending=False)

In [ ]:
df_3

,publication_date,company,title,position,link_url
3,2022-08-20,Deloitte Advisory,AI LAB,Trainee,http://nofluffjobs.com/pl/job/ai-lab-deloitte-...
4,2022-08-19,Webinterpret,Junior Data Scientist,Junior,http://nofluffjobs.com/pl/job/junior-data-scie...
0,2022-08-18,Amartus Polska Sp. z o.o.,Junior Phyton Developer,Junior,http://nofluffjobs.com/pl/job/junior-phyton-de...
1,2022-08-18,IDEA team within Narodowe Centrum Badań Jądrowych,Junior Python Developer,Junior,http://nofluffjobs.com/pl/job/junior-python-de...
2,2022-08-18,Devire,Python Developer (Data Science),Junior,http://nofluffjobs.com/pl/job/python-developer...
6,2022-08-17,Astrotectonic,Junior Data Scientist,Junior,http://nofluffjobs.com/pl/job/junior-data-scie...
8,2022-08-14,Bertek Sp. z o.o.,Junior Python Developer,Junior,https://bulldogjob.pl/companies/jobs/113373-ju...
5,2022-08-08,Sport Vision Technology sp. z o.o. sp. k.,Junior AI Developer,Junior,http://nofluffjobs.com/pl/job/junior-ai-develo...
7,2022-07-23,Accenture Polska,Junior Data Engineer with Python (Communicatio...,Junior,https://bulldogjob.pl/companies/jobs/120362-ju...